# Playing with Jupyter

### Examples of Markdown
# H1
## H2
### H3
#### H4
##### H5
###### H6

Italics, with *asterisks*
Bold, with **asterisks**

1. First ordered list item
2. Another item
⋅⋅⋅⋅* Unordered sub-list.

[I'm an inline-style link](https://www.google.com)

Inline `code` has `back-ticks around` it.

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

In [108]:
# Python Code Block
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

## Using Pandas

Pandas is an open-source Python library designed for data manipulation and analysis. It makes working with structured data fast, flexible, and intuitive — especially if you're dealing with CSV files, Excel sheets, SQL tables, JSON, or APIs.

The two core data structures in Pandas are:

* Series: A 1D labeled array (like a column)
* DataFrame: A 2D labeled data structure (like a full spreadsheet or SQL table)

### What Is A DataFrame

A **DataFrame** is a two-dimensional, tabular data structure with labeled rows and columns. Think of it as a Python-native spreadsheet — but way more powerful and programmable.

### Key Features:
* Label-based indexing
* Column-wise and row-wise operations
* Support for mixed data types
* Fast, vectorized operations (built on NumPy)

In [109]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Country': ['USA', 'Canada', 'UK']
}

df = pd.DataFrame(data)
print(df)

      Name  Age Country
0    Alice   25     USA
1      Bob   30  Canada
2  Charlie   35      UK

In [110]:

import pandas as pd

dfc = pd.read_csv('orders.csv')        # Load from CSV
dfc.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [111]:
import openpyxl

df = pd.read_excel('orders.xls', sheet_name='orders') # read in same data from an excel file
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

### Explore A DataFrame

In [112]:
df.info()        # Column types and non-null values

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     str
 2   Product       40 non-null     str
 3   Category      40 non-null     str
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     datetime64[us]
 7   Shipped       40 non-null     str
 8   Country       40 non-null     str
dtypes: datetime64[us](1), float64(1), int64(2), str(5)
memory usage: 2.9 KB

In [113]:
df.describe()    # Summary stats

           OrderID    Quantity        Price            OrderDate
count    40.000000   40.000000    40.000000                   40
mean   1020.500000    5.450000   106.457500  2024-06-21 11:24:00
min    1001.000000    1.000000     0.800000  2024-06-01 00:00:00
25%    1010.750000    1.000000    18.000000  2024-06-11 18:00:00
50%    1020.500000    1.000000    43.500000  2024-06-21 12:00:00
75%    1030.250000    2.250000   112.500000  2024-07-01 06:00:00
max    1040.000000  100.000000  1200.000000  2024-07-11 00:00:00
std      11.690452   15.903475   201.091854                  NaN

In [114]:
df.columns       # Column names

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')

In [115]:
df.index         # Row indices

RangeIndex(start=0, stop=40, step=1)

In [116]:
df["Country"] # returns column entry (series) (all countries in table)

0              USA
1           Canada
2              UAE
3        Singapore
4           Mexico
5              UAE
6               UK
7      South Korea
8            Italy
9            Japan
10          France
11           India
12       Australia
13           Spain
14           China
15           Egypt
16          Poland
17             USA
18           Japan
19    Saudi Arabia
20          Canada
21          Brazil
22         Germany
23        Pakistan
24          Sweden
25          France
26       Argentina
27          Russia
28     South Korea
29           Italy
30         Morocco
31         Germany
32        Colombia
33             USA
34           Japan
35              UK
36        Portugal
37            Iran
38     South Korea
39         Ukraine
Name: Country, dtype: str

In [117]:

#df = df.reset_index()  # Make sure indexes pair with number of rows

for index, row in df.iterrows():
    print('Country: ',row['Country'], 'Customer: ',row['CustomerName'])

Country:  USA Customer:  John Smith
Country:  Canada Customer:  Sarah Lee
Country:  UAE Customer:  Ali Khan
Country:  Singapore Customer:  Alice Wong
Country:  Mexico Customer:  Carlos Mendez
Country:  UAE Customer:  Nora Ibrahim
Country:  UK Customer:  Emily Davis
Country:  South Korea Customer:  James Park
Country:  Italy Customer:  Maria Rossi
Country:  Japan Customer:  Takeshi Nakamura
Country:  France Customer:  Sophie Martin
Country:  India Customer:  Raj Patel
Country:  Australia Customer:  Emma Wilson
Country:  Spain Customer:  Diego Rodriguez
Country:  China Customer:  Lisa Chen
Country:  Egypt Customer:  Ahmed Hassan
Country:  Poland Customer:  Anna Kowalski
Country:  USA Customer:  Michael Brown
Country:  Japan Customer:  Yuki Tanaka
Country:  Saudi Arabia Customer:  Fatima Al-Zahra
Country:  Canada Customer:  David Thompson
Country:  Brazil Customer:  Isabella Silva
Country:  Germany Customer:  Oliver Schmidt
Country:  Pakistan Customer:  Zara Ahmed
Country:  Sweden Customer:  Lucas Anderson
Country:  France Customer:  Chloe Dubois
Country:  Argentina Customer:  Miguel Torres
Country:  Russia Customer:  Nina Petrov
Country:  South Korea Customer:  Seo-yeon Kim
Country:  Italy Customer:  Giuseppe Romano
Country:  Morocco Customer:  Amira Hassan
Country:  Germany Customer:  Thomas M√ºller
Country:  Colombia Customer:  Sofia Rodriguez
Country:  USA Customer:  Alex Johnson
Country:  Japan Customer:  Yuki Yamamoto
Country:  UK Customer:  Emma Thompson
Country:  Portugal Customer:  Carlos Santos
Country:  Iran Customer:  Leila Mansouri
Country:  South Korea Customer:  Daniel Kim
Country:  Ukraine Customer:  Anna Ivanova

In [118]:
len(dfe["Country"])

40


#### Basic Access

In [119]:
df['Product']

0                    Laptop
1                Headphones
2              Office Chair
3                 Desk Lamp
4                  Keyboard
5                  Notebook
6             Standing Desk
7                   Monitor
8                       Pen
9                     Mouse
10                   Webcam
11             File Cabinet
12                  Stapler
13                USB Drive
14                Bookshelf
15            Printer Paper
16           Wireless Mouse
17           Desk Organizer
18               Calculator
19               Whiteboard
20             Highlighters
21        Bluetooth Speaker
22             Office Plant
23             Sticky Notes
24             Tablet Stand
25           Paper Shredder
26           Desk Chair Mat
27             Binder Clips
28        Wireless Keyboard
29            Desk Calendar
30                  USB Hub
31         Document Scanner
32    Desk Drawer Organizer
33              Index Cards
34            Monitor Stand
35       Desk Lamp with USB
36         Wireless Earbuds
37                 Desk Pad
38              Power Strip
39               Desk Clock
Name: Product, dtype: str

In [120]:
df.iloc[10]

OrderID                        1011
CustomerName          Sophie Martin
Product                      Webcam
Category                Electronics
Quantity                          1
Price                          85.0
OrderDate       2024-06-12 00:00:00
Shipped                         Yes
Country                      France
Name: 10, dtype: object

In [121]:
df[df['Product']=='Calculator']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan

In [122]:
df[(df['Price'] < 50) & (df['Quantity'] > 50)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [125]:
df[df['CustomerName'].str.startswith('A')]         # Names starting with A

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [ ]:
df[~df['Country'].isin(['Canada'])]        # NOT condition

      Name  Age Country
0    Alice   25     USA
2  Charlie   35      UK

In [ ]:
df[df['Country'].isin(['USA', 'UK'])]      # Match multiple values

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK

In [126]:
df['Country'] = df['Country'].str.upper()
df['Country']

0              USA
1           CANADA
2              UAE
3        SINGAPORE
4           MEXICO
5              UAE
6               UK
7      SOUTH KOREA
8            ITALY
9            JAPAN
10          FRANCE
11           INDIA
12       AUSTRALIA
13           SPAIN
14           CHINA
15           EGYPT
16          POLAND
17             USA
18           JAPAN
19    SAUDI ARABIA
20          CANADA
21          BRAZIL
22         GERMANY
23        PAKISTAN
24          SWEDEN
25          FRANCE
26       ARGENTINA
27          RUSSIA
28     SOUTH KOREA
29           ITALY
30         MOROCCO
31         GERMANY
32        COLOMBIA
33             USA
34           JAPAN
35              UK
36        PORTUGAL
37            IRAN
38     SOUTH KOREA
39         UKRAINE
Name: Country, dtype: str