In [1]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Country': ['USA', 'Canada', 'UK']
}
df = pd.DataFrame(data)
print(df)

      Name  Age Country
0    Alice   25     USA
1      Bob   30  Canada
2  Charlie   35      UK

In [2]:
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [ ]:
import pandas as pd
df = pd.read_csv('expenses.csv')
df.head()

                  Date Category        Description  Amount
0  2026-03-20 13:28:53     Food              Tacos     5.0
1  2026-03-21 14:12:48      Fun             Movies   200.0
2  2026-03-21 14:41:20     Rent    Monthly Housing   400.0
3  2026-03-21 14:41:28     Food  Monthly Groceries   500.0
4  2026-03-21 19:13:00      Fun        Video Games    50.0

In [ ]:
df[df['Category'] == 'Fun']

                  Date Category  Description  Amount
1  2026-03-21 14:12:48      Fun       Movies   200.0
4  2026-03-21 19:13:00      Fun  Video Games    50.0

In [ ]:
max_row = df.loc[df['Amount'].idxmax()]['Category']

print(max_row)

Food